name: dio_workspace
repository: https://github.com/cfug/dio

packages:
  - 'dio'
  - 'plugins/*'
  - 'plugins/**/example*'
  - 'example*'
  - 'dio_tests'

ide:
  intellij:
    enabled: true
    moduleNamePrefix: ''

command:
  bootstrap:
    runPubGetInParallel: false
