name: dio_workspace
repository: https://github.com/cfug/dio

packages:
  - dio
  - plugins/*
  - example*

ide:
  intellij:
    enabled: true
    moduleNamePrefix: ''

command:
  bootstrap:
    runPubGetInParallel: false
