name: 👷 Infra
description: Something is wrong with the CI setup or could be improved
labels: ["infra"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Request Statement
    validations:
      required: true
