name: Publish from comments

on:
  issue_comment:
    types: [created]

jobs:
  publish:
    permissions:
      contents: write
    # https://github.com/cfug/dio/issues/1633
    if: github.event.issue.number == 1633
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          token: ${{ secrets.CFUG_PUBLISHER }}
      - uses: dart-lang/setup-dart@2bd11704788983a6a210731656d0042e2df8b2c1
      - uses: cfug/dio_issue_release_action@fabea0c8c802678977470bae92a317a5af94209b
        with:
          github-token: ${{ secrets.CFUG_PUBLISHER }}
          pub-credentials-json: ${{ secrets.CREDENTIAL_JSON }}
