name: Publish from comments

on:
  issue_comment:
    types: [created]

jobs:
  publish:
    permissions:
      contents: write
    # https://github.com/cfug/dio/issues/1633
    if: github.event.issue.number == 1633
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          token: ${{ secrets.CFUG_PUBLISHER }}
      - uses: dart-lang/setup-dart@10b57efefac07722403c8b9c95fa68bb09276def
      - uses: cfug/dio_issue_release_action@fabea0c8c802678977470bae92a317a5af94209b
        with:
          github-token: ${{ secrets.CFUG_PUBLISHER }}
          pub-credentials-json: ${{ secrets.CREDENTIAL_JSON }}
