name: Publish from comments

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

# Disable permissions for all of the available permissions
permissions: {}

jobs:
  publish:
    permissions:
      contents: write
    # https://github.com/cfug/dio/issues/1633
    if: github.event.issue.number == 1633
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
          token: ${{ secrets.CFUG_PUBLISHER }}
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 #v1.8.0
      - uses: cfug/dio_issue_release_action@fabea0c8c802678977470bae92a317a5af94209b #v2.4.1
        with:
          github-token: ${{ secrets.CFUG_PUBLISHER }}
          pub-credentials-json: ${{ secrets.CREDENTIAL_JSON }}
